name: Auto-Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Se ejecuta una vez al día (a la medianoche UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script de generación
        run: |
          python generar_readme.py

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-actualización del README"
          git push
